### PR TITLE
fix: vector search is ignoring the currently selected organization

### LINKED ISSUE #133: bug: vector search is ignoring the currently selected organization
## Summary

The vector search index page + popup should take the current organization scope into consideration - right now it's ignoring scoping.

### PR DESCRIPTION
**Pull request by gsobczyk**
## Summary

The vector search index listing and the global search popup were ignoring the current organization scope, which could
surface tenant-wide results outside the user’s active org context. This change resolves organization scope from the
request and applies it consistently across the search and index endpoints (and the pgvector driver), aligning UI + API
behavior with org scoping expectations.

## Changes

- Apply `resolveOrganizationScopeForRequest(...)` to `/api/search/index`, `/api/search/search`, and
  `/api/search/search/global`
- Enforce strict org filtering in the pgvector driver (no implicit “include org NULL” fallback)
- Add a small UI hint (“Scoped to current organization”) to the hybrid search page and global search dialog
- Add Jest route tests validating organization scoping behavior

## Specification

**Does a spec exist for this feature/module?**

- [ ] Yes
- [ ] No (created a new spec)
- [x] N/A (minor change, no spec needed)

**Spec file path:** N/A

## Testing

- `yarn test -- --filter=@open-mercato/search` (Jest route tests for org scoping)
- manual

## Checklist

- [x] This pull request targets `develop`.
- [x] I have read and accept the Open Mercato Contributor License Agreement (see `docs/cla.md`).
- [x] I updated documentation, locales, or generators if the change requires it.
- [x] I added or adjusted tests that cover the change.
- [ ] I added or updated integration tests in `.ai/qa/tests/` (or documented why integration coverage is not required).
- [x] I created or updated the spec in `.ai/specs/` with a changelog entry (if applicable).

## Linked issues

Fixes #133

### CODE REVIEW

File: packages/search/src/modules/search/api/index/route.ts [hunk 1]
```diff
@@ -75,9 +76,15 @@ export async function GET(req: Request) {
     }
 
     // List vector entries via the strategy
+    const scope = await resolveOrganizationScopeForRequest({ container, auth, request: req })
+    if (Array.isArray(scope.filterIds) && scope.filterIds.length === 0) {
+      return NextResponse.json({ entries: [], limit, offset })
+    }
+    const organizationId =
+      typeof scope.selectedId === 'string' && scope.selectedId.trim().length > 0 ? scope.selectedId.trim() : undefined
```
Comment (fto-aubergine) [inline packages/search/src/modules/search/api/index/route.ts:84]: The org ID normalization pattern (typeof x === 'string' && x.trim().length > 0 ?
  x.trim() : ...) is repeated few times — consider extracting a small helper.

File: packages/search/src/modules/search/frontend/components/GlobalSearchDialog.tsx [hunk 2]
```diff
@@ -334,6 +334,9 @@ export function GlobalSearchDialog({
             {showVectorWarning ? (
               <p className="rounded bg-amber-100 dark:bg-amber-900/20 px-3 py-2 text-sm text-amber-800 dark:text-amber-200">{missingConfigMessage}</p>
             ) : null}
+            <p className="text-xs text-muted-foreground">
+              {t('search.scopeHint.currentOrg', 'Scoped to current organization')}
+            </p>
```
Comment (fto-aubergine) [inline packages/search/src/modules/search/frontend/components/GlobalSearchDialog.tsx]: The "Scoped to current organization" hint renders even when no org is selected (e.g.
  super admin with "all organizations"). It should be conditional — only shown when an
  org is actually active, or show a different message when unscoped.
