### PR TITLE
fix: missing asterisk

### LINKED ISSUE #1588: bug: [UI / Scheduler] Required field "Target Queue" is not marked with an asterisk in the Create Schedule form
## Summary
The **Target Queue** field in the Create Schedule form is functionally required — the form cannot be submitted without it — but the field is not marked with an asterisk (`*`) like other required fields. This is inconsistent with the form's own validation behaviour and violates the UI convention used throughout the app.

## Steps to reproduce
1. Navigate to the **Scheduled Jobs** page and click **Create Schedule**.
2. Observe the form fields — note which ones are marked with `*` (required indicator).
3. Locate the **Target Queue** field — it has no `*`.
4. Attempt to submit the form without filling in Target Queue.
5. Observe: the form blocks submission, indicating the field is required.

## Expected result
The **Target Queue** field should be marked with `*` to indicate it is required, consistent with other required fields in the same form and throughout the application.

## Actual result
The field is required in practice but visually appears optional. Users have no visual indication that omitting it will prevent form submission.

Image

## Environment
- Branch: `develop`
- Module or area: Scheduler / Create Schedule form / UI
- Browser/Runtime: Edge

## Additional context
Minor UX inconsistency, but worth fixing to maintain form conventions. If Target Queue is conditionally required (e.g. only when Target Type is "queue"), the asterisk should appear/disappear dynamically based on the selected Target Type — and the conditional requirement should be reflected in the field label or helper text.

### PR DESCRIPTION
**Pull request by Sawarz**
## Summary
The Create Schedule form treats **Target Queue** (when Target Type is Queue) and **Target Command** (when Target Type is Command) as required for submission, but those fields were rendered inside a custom `CrudForm` field with plain labels—so they never received the same red **\*** used for other required fields. Labels now match `CrudForm`’s required styling (`block text-sm font-medium` + `<span className="text-red-600"> *</span>`), and the asterisk only appears for the active target type.

## Changes
- Update `packages/scheduler/src/modules/scheduler/lib/scheduledJobFormConfig.tsx`: replace custom `Label` wrappers for Target Queue / Target Command with the same label + required asterisk pattern as `CrudForm`.
- 
## Specification
**Does a spec exist for this feature/module?**
- [ ] Yes
- [ ] No (created a new spec)
- [x] N/A (minor change, no spec needed)

## Testing
- `read_lints` on `scheduledJobFormConfig.tsx` (clean).
- Manual: `yarn dev` → `/backend/config/scheduled-jobs/new` → confirm **\*** on **Target Queue** with Target Type **Queue**; switch to **Command** and confirm **\*** on **Target Command** and no queue asterisk.

## Checklist
- [x] This pull request targets `develop`.
- [ ] I have read and accept the Open Mercato Contributor License Agreement (see `docs/cla.md`).
- [ ] I updated documentation, locales, or generators if the change requires it.
- [ ] I added or adjusted tests that cover the change.
- [ ] I added or updated integration tests in `.ai/qa/tests/` (or documented why integration coverage is not required).
- [ ] I created or updated the spec in `.ai/specs/` with a changelog entry (if applicable).

## Linked issues
Fixes #1588

### CODE REVIEW

File: packages/scheduler/src/modules/scheduler/lib/scheduledJobFormConfig.tsx [hunk 1]
```diff
@@ -224,9 +224,10 @@ export function scheduledJobFields(
           <div className="space-y-4">
             {targetType === 'queue' && (
               <div className="space-y-1">
-                <Label htmlFor="targetQueue">
+                <label htmlFor="targetQueue" className="block text-sm font-medium">
```
Comment (pkarw) [inline packages/scheduler/src/modules/scheduler/lib/scheduledJobFormConfig.tsx]: ok but why changed to `label`?

File: packages/scheduler/src/modules/scheduler/lib/scheduledJobFormConfig.tsx [hunk 2]
```diff
@@ -238,9 +239,10 @@ export function scheduledJobFields(
             )}
             {targetType === 'command' && (
               <div className="space-y-1">
-                <Label htmlFor="targetCommand">
+                <label htmlFor="targetCommand" className="block text-sm font-medium">
                   {t('scheduler.form.target_command', 'Target Command')}
-                </Label>
+                  <span className="text-red-600"> *</span>
```
Comment (pkarw) [inline packages/scheduler/src/modules/scheduler/lib/scheduledJobFormConfig.tsx]: Please do use the colors from Design System defined by @zielivia

**Review by pkarw — CHANGES_REQUESTED** [review]

**Comment by pkarw** [comment]
Opened #1607 to supersede this PR with the design-system `text-status-error-icon` token and a regression test covering both queue and command target types.

**Comment by pkarw** [comment]
Opened #1607 as a superseding fix that uses the design-system `text-status-error-icon` token (the same marker the shared FormField primitive uses) and adds Jest coverage for both `queue` and `command` target types.
