### PR TITLE
fix: #303 filters tags panel stabilization

### LINKED ISSUE #303: bug: Tags filter triggers excessive /api/sales/tags requests causing jumping suggestions panel
## Summary

The Tags filter field triggers excessive GET /api/sales/tags requests and causes the suggestions panel to “jump.” On focusing the field (without typing) and especially after typing the first character, a burst of requests is issued and the suggestions list visibly jitters between loading and loaded states.
It should be fixed for all places which are using tags in filters tab. 

## Steps to reproduce

1.Open the Sales Documents list (Quotes/Orders) and open the Filters panel.
2.Click into the “Tags” filter field. Observe the Network tab in DevTools.
3.Type the first character (e.g., “a”) and wait briefly

## Expected result

•No requests on focus alone (empty query should not trigger a fetch).
•After typing 1+ character, a single request is sent after the debounce; the suggestions list remains stable (no jumping).

## Actual result

• Focusing the field and typing the first character triggers a series of GET /api/sales/tags requests (often every ~50–100 ms), and the suggestions panel jitters as the state flips between loading and loaded.
• Example logs:
GET /api/sales/tags?page=1&pageSize=50 200 in 44–86 ms, repeated many times in short succession.

## Environment

- Branch: `develop`

### PR DESCRIPTION
**Pull request by piotr-lewczuk**
## Summary
Stabilize reference to filters tags in order to avoid constant reloading on focus. Default already implemented debouncing of 200ms is used. 

Additional changes in separate commit which are fixing problems with app startup on Windows

## Changes

- stabilization code based on filtersSingature instead of filters introduced in FilterOverlay
- fixes for windows app startup in start.ts and utils.ts scripts

## Testing

Running up app with yarn dev
Go to orders
Click filters
Click tags - reloading does not happen for empty input box
Try typing - proper amount of request based on debounce time are made

Result visible on attached screen shot: 
Bez tytułu

## Checklist

- [x] This pull request targets `develop`.
- [x] I have read and accept the Open Mercato Contributor License Agreement (see `docs/cla.md`).
- [-] I updated documentation, locales, or generators if the change requires it.
- [-] I added or adjusted tests that cover the change.

## Linked issues

Fixes #303

### CODE REVIEW

File: scripts/start.ts [hunk 1]
```diff
@@ -20,25 +21,32 @@ async function main() {
 
   console.log(`[start] Starting Open Mercato in ${mode} mode...`)
 
+  // Resolve local binaries from node_modules/.bin to avoid relying on global npx
+  const isWin = process.platform === 'win32'
+  const bin = (name: string) =>
+    path.resolve(process.cwd(), 'node_modules', '.bin', isWin ? `${name}.cmd` : name)
```
Comment (pkarw) [inline scripts/start.ts:27]: Have you tested it on Windows? Do we really have the `*.cmd` files?

**Review by pkarw — CHANGES_REQUESTED** [review]
Great job, just one question added regarding Windows support

File: scripts/start.ts (hunk 1 above)
Comment (piotr-lewczuk) [reply scripts/start.ts:27]: Yes, I tested it, as I run Open Mercato only on Windows. When running with shell: false, the executable in the path must have the .cmd extension. At the moment we have a double defence mechanism. If we are confident that on Windows we will always execute it with shell: true (which is most likely the case), then this additional handling might be a bit of over-engineering.
