### PR TITLE
fix(search): keep session on global search 403 and show permission message

### LINKED ISSUE #1005: bug: Unauthorized search access logs out user instead of showing permission error
## Summary

When a user without search.view permission uses the global search, the system logs them out instead of handling the authorization error gracefully.

## Steps to reproduce

1. Login as Employee 
2. Click on the Search input in the top bar
3. Type at least 2 characters

## Expected result

The system should:

- either disable search input for unauthorized users
- or show a non-blocking error message (e.g. "You don’t have permission")

User should remain logged in.

## Actual result

After typing 2 characters:

- a brief Forbidden appears
- user is automatically logged out
- redirected to login page with message:

`You don't have access to this feature (search.view). Please contact your administrator.`

Image

Image

## Environment

- Branch: `develop`
- Module or area: Search
- Browser/Runtime: Edge

## Additional context

This indicates improper handling of authorization errors (likely 403 → logout).
Unauthorized access should not invalidate user session.

### PR DESCRIPTION
**Pull request by muhammadusman586**
## Summary
This PR fixes an issue where users without `search.view` permission were logged out when using Global Search.

Closes #1005.

## Problem
When Global Search returned `403 Forbidden`, the shared API fetch flow treated it like an auth redirect case and sent users to login.  
This caused an unexpected logout/redirect instead of showing a permission error in place.

## Root Cause
Global Search requests were using the shared forbidden redirect behavior in the backend UI API utility.  
So authorization failure (`403`) triggered redirect logic rather than dialog-level error handling.

## What Changed
- Added a request-level opt-out for automatic `403` login redirect in shared API fetch behavior.
- Applied this opt-out specifically to Global Search requests.
- Improved Global Search dialog error handling:
  - Detects unauthorized/forbidden responses and shows a user-friendly permission message.
- Added i18n message key for permission-denied state in all search locales.

## User Impact
- Unauthorized users now remain logged in.
- Global Search shows a clear message:
  - "You do not have permission to use global search."
- Authorized users’ search behavior is unchanged.

## Scope / Safety
- Scoped to Global Search request path.
- `401` session-expired handling remains unchanged.
- Existing redirect behavior for other `403`-protected flows remains unchanged unless explicitly opted out.

## Manual Test Plan
1. Login as a user without `search.view`.
2. Open Global Search and type at least 2 characters.
3. Verify:
   - No logout occurs.
   - No redirect to login occurs.
   - Permission message is shown in the dialog.
4. Login as a user with `search.view`.
5. Verify Global Search still works normally and returns results.

### CODE REVIEW

**Comment by muhammadusman586** [comment]
> It works! thank you @muhammadusman586 It can be merged. :) @pkarw image

Thanks @alinadivante glad it’s working!

File: packages/ui/src/backend/utils/api.ts [hunk 1]
```diff
@@ -157,7 +158,18 @@ export async function apiFetch(input: RequestInfo | URL, init?: RequestInit): Pr
...
+      try {
+        const parsed = JSON.parse(raw)
+        if (parsed && typeof parsed === 'object') {
+          if (typeof (parsed as { error?: unknown }).error === 'string') {
+            msg = (parsed as { error: string }).error
+          } else if (typeof (parsed as { message?: unknown }).message === 'string') {
+            msg = (parsed as { message: string }).message
+          }
+        }
+      } catch {}
```
Comment (pkarw) [inline packages/ui/src/backend/utils/api.ts]: we've got a helper `readJsonSafe` maybe use it an yways please do not keep the empty catch

**Comment by muhammadusman586** [comment]
> PLease just apply the one remaining fix

Hi @pkarw,

Thanks for the feedback! I will update this to use readJsonSafe and remove the empty catch. I will push the fix shortly.
